import { ResumeDownload } from "@/components/ResumeDownload";
import { Skills } from "@/components/Skills";
import { Testimonials } from "@/components/Testimonials";
import { experience } from "@/lib/about";

export const metadata = { title: "About | Prashant Dahal", description: "About Prashant Dahal, a creative developer focused on high-performance interfaces and motion systems." };

export default function AboutPage() {
  return <main className="min-h-screen"><section className="mx-auto max-w-6xl px-6 py-24 sm:py-32"><p className="text-xs font-medium tracking-[0.22em] text-cyan-200">ABOUT</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-semibold tracking-tight sm:text-7xl">I turn thoughtful interaction into clear digital experiences.</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-gray-300">I am Prashant Dahal, a creative developer working at the intersection of interface design, frontend engineering, and motion. I care about the details people feel: timing, hierarchy, responsiveness, and the quiet confidence of a system that works.</p><div className="mt-10"><ResumeDownload /></div></section><section className="mx-auto max-w-6xl px-6 py-24 sm:py-32"><div className="max-w-2xl"><p className="text-xs font-medium tracking-[0.22em] text-fuchsia-200">EXPERIENCE</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">A practice built through making.</h2></div><div className="mt-10 space-y-8">{experience.map((item) => <article key={`${item.company}-${item.role}`} className="grid gap-4 border-t border-white/10 pt-6 md:grid-cols-[12rem_1fr]"><p className="text-sm text-gray-400">{item.dates}</p><div><h3 className="text-xl font-semibold">{item.role}</h3><p className="mt-1 text-cyan-200">{item.company}</p><ul className="mt-4 space-y-2 text-gray-300">{item.achievements.map((achievement) => <li key={achievement}>• {achievement}</li>)}</ul></div></article>)}</div><div className="mt-16 grid gap-8 border-t border-white/10 pt-8 md:grid-cols-2"><div><p className="text-xs tracking-[0.18em] text-gray-400">EDUCATION</p><h3 className="mt-3 text-xl font-semibold">Self-directed, project-led learning</h3><p className="mt-3 leading-7 text-gray-300">Continuous study through shipped interfaces, documentation, accessibility practice, and open-source exploration.</p></div><div><p className="text-xs tracking-[0.18em] text-gray-400">WORKING STYLE</p><h3 className="mt-3 text-xl font-semibold">Curious, precise, collaborative</h3><p className="mt-3 leading-7 text-gray-300">I like to make the system understandable as well as the final screen memorable.</p></div></div></section><Skills /><Testimonials /></main>;
}
